stages:
  - build
  - test-job
  - deploy
build-job:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
  script:
    - docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE .
    - docker push $DOCKER_USERNAME/$DOCKER_IMAGE
test-job:
  stage: test
  script:
    - echo "testing"

deploy:
  stage: deploy
  image:
    name: dtzar/helm-kubectl
    entrypoint: ['']
  before_script:
    - kubectl config get-contexts
    - kubectl config use-context technical_challange/berkeley_project:cicd-agent
  script:
    - kubectl apply -f k8s/manifests/ingress-controller.yaml
    - helm install go-app-sit ./helm/go-app-chart -f ./helm/go-app-chart/sit_values.yaml
