
apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: {{ .Values.namespace }}
  labels:
    app: go-app

spec:
  selector:
    app: go-app

  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080