apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-app
spec:
  rules:
  - host: berkeley.bhargavi.life
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-app
            port:
              number: 8080
  ingressClassName: nginx